// Practice 5

// 1 
df.select(approx_count_distinct("Sales")).show()

// 2 
df.select(avg("Sales")).show()

// 3 
df.select(collect_list("Sales")).show()

// 4 
df.select(collect_set("Sales")).show()

// 5
df.select(first("Sales")).show()

// 6 
df.select(kurtosis("Sales")).show()

// 7
df.select(last("Sales")).show()

// 8 
df.select(skewness("Sales")).show()

// 9

// 10

// 11

// 12

// 13

// 14

// 15
